### ISSUE TITLE
Add support for the KServe `inputs` format

### ISSUE THREAD

**Issue by ruivieira** [trustyai-python/trustyai-explainability#459]
Add support for the KServe "inputs" format.

## Example:

Input:

```json
{
    "inputs": [
      {
        "name": "input-0",
        "shape": [1, 4],
        "datatype": "FP32",
        "data": [
          [32, 0, 1, 2]
        ]
      }
    ]
  }
```

Output:

```json
{"model_name":"example-isvc","id":"04f66a85-a54d-4a9c-aa5e-5f4514cb4def","parameters":{},"outputs":[{"name":"predict","shape":[1,1],"datatype":"INT64","data":[0]}]}
```

## Validation

Assuming

- A KServe installation
- A namespace `test`
- A test model like the below, deployed in `test`
- A `TrustyAIService` CR deployed in `test`.

Model:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: income-isvc
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: "https://github.com/trustyai-explainability/trustyai-explainability/raw/e3a0de0f73bffb764c65e44ccc7f40735104bb9d/explainability-service/demo/models/model.joblib"
```

And an example payload (e.g. in `payload.json`):

```json
{
    "inputs": [
      {
        "name": "input-0",
        "shape": [1, 4],
        "datatype": "FP32",
        "data": [
          [32, 0, 1, 2]
        ]
      }
    ]
  }
```

Issuing an inference request to the model (`localhost` added for simplicity, adapt to the model's ingress), e.g.

```shell
curl -v \
  -H "Host: ${SERVICE_HOSTNAME}" \
  -H "Content-Type: application/json" \
  -d @./payload.json \
  http://localhost:8080/v2/models/income-isvc/infer
```

Should be correctly parsed by the `TrustyAIService`. This can be verified either from the `TrustyAIService` logs, which will report a payload reconciliation, or by inspecting the existence of the data files in the `TrustyAIService` storage.
